version: '3.9'



name: chatbot

# We use secret here
secrets:
  conf:
    file: ./secrets/config.ini
  servant_conf:
    file: ./secrets/servant_conf.ini

# We connect all services through docker brigde
networks:
  master:
    driver: bridge


services:
# This is the main service we provide
# The chatbot service
  master_server:
    build: ./service/MasterServer
    image: parkerint64/chatbot_master_server
    environment:
    # In our program, we use this varibale to indicate 
    # if we're in container env or not
      - CURRENT_RUN_MODE=docker
      - CONFIG_FILE=/run/secrets/conf
    ports:
      - "4534:4534" # port forward, 4534  -> 4534

    secrets:
      - conf
    
    networks:
      - master

  servent_server:
    build: ./service/ServantServer
    image: parkerint64/chatbot_servant_server
    environment:
      - CURRENT_RUN_MODE=docker
      - CONFIG_FILE=/run/secrets/servant_conf
    
    secrets:
      - servant_conf

    networks:
      - master

    depends_on:
      - master_server
