version: '3.9'



name: chatbot

# We use secret here
secrets:
  conf:
    file: ./secrets/config.ini
  servant_conf:
    file: ./secrets/servant_conf.ini


services:
# This is the main service we provide
# The chatbot service
  master_server:
    build: ./service/MasterServer
    environment:
    # In our program, we use this varibale to indicate if we're in container env or not
      - CURRENT_RUN_MODE=docker    
      - CONFIG_FILE=/run/secrets/conf
    ports:
      - "8000:8000" # port forward, 8000 -> 8000

    secrets:
      - conf

  servent_server:
    build: ./service/ServantServer
    environment:
      - CURRENT_RUN_MODE=docker
      - CONFIG_FILE=/run/secrets/servant_conf
    
    secrets:
      - servant_conf
    depends_on:
      - master_server
