name: Cloud-deploy
on:
  push:
    branches:
      - main  # or any branch you want to deploy from

jobs:
  deploy:
    runs-on: self-hosted  # Make sure this matches your self-hosted runner's label
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd /home/docker_deploy/COMP7940_Group_Project
            git pull
            docker compose down
            docker rmi -f parkerint64/chatbot_servant_server
            docker rmi -f parkerint64/chatbot_master_server
            docker compose up --build -d
