name: render-deploy
run-name: Deploy to render
on: 
  [push, pull_request]:
    branches:
      - main

jobs:
  deploy:
    name: Deploy app
    runs-on: self-hosted
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v2
      - name: Clone to the remote
        run: git clone https://github.com/parker-int64/COMP7940_Group_Project.git && cd COMP7940_Group_Project
      - name: Stop the current compose job
        run: docker compose down
      - name: Deleting previous images
        run: docker rmi -f parkerint64/chatbot_servant_server
        run: docker rmi -f parkerint64/chatbot_master_server
        run: docker rmi -f <none> # optional, incase we rebuild a image with empty name
      - name: Rebuild the images and launch the app.
        run: docker compose up -d --build # build & run
